---
version: "2.1"
services:
  code-server:
    image: linuxserver/code-server
    container_name: code-server-master
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=master
      - SUDO_PASSWORD=master
      - PROXY_DOMAIN=vscode.dathaddenwetochafgesproken.nl #optional
    volumes:
      - ~/docker/code-server-master:/config
      - ~/docker/code-server-user1/workspace:/config/workspace/user1
      - ~/docker/code-server-user2/workspace:/config/workspace/user2
    ports:
      - 8443:8443
    restart: unless-stopped

  code-server-1:
    image: linuxserver/code-server
    container_name: code-server-user1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=user1
      - SUDO_PASSWORD=user1
      - PROXY_DOMAIN=vsuser1.dathaddenwetochafgesproken.nl #optional
    volumes:
      - ~/docker/code-server-user1:/config
    ports:
      - 8444:8443
    restart: unless-stopped

  code-server-2:
    image: linuxserver/code-server
    container_name: code-server-user2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=user2
      - SUDO_PASSWORD=user2
      - PROXY_DOMAIN=vsuser2.dathaddenwetochafgesproken.nl #optional
    volumes:
      - ~/docker/code-server-user2:/config
    ports:
      - 8445:8443
    restart: unless-stopped

  nginx-proxy-manager:
    image: jlesage/nginx-proxy-manager
    build: .
    ports:
      - "8181:8181"
      - "80:8080"
      - "443:4443"
    volumes:
      - "~/docker/nginx-proxy-manager:/config:rw"
    restart: unless-stopped
